version: "3.5"
services:
  django:
    build:
      dockerfile: ./docker/django/Dockerfile
      context: '.'
      args:
        PYTHON_VERSION: 3.8-slim
    ports:
      - "8000"
    environment:
      # Development libraries will be installed to volume
      PYTHONPATH: "home/circular/.local/lib/python3.8/site-packages/"
    volumes:
      - ./src/:/src/
      - cache:/home/circular/.cache
      - local:/home/circular/.local
volumes:
  cache:
  local:
