version: 2
jobs:
  build:
    docker:
      # using custom image, see .circleci/images/primary/Dockerfile
      - image: circleci/python:3.8

    environment:
      TEST_RESULTS: /tmp/test-result
      COMPOSE_FILE: docker-compose-ci.yml

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: "Docker Compose Build"
          command: |
            docker-compose -f ${COMPOSE_FILE} build --build-arg UID=$UID
      - run:
          name: "Install packages"
          command: |
            docker-compose -f ${COMPOSE_FILE} run django poetry install
      - run:
          name: "Run tests"
          command: |
            mkdir test-results
            docker-compose -f ${COMPOSE_FILE} run django python -m pytest || exit 0
            docker-compose -f ${COMPOSE_FILE} run --rm django ls /test-results/
      - store_test_results:
          path: test-results
