version: 2
jobs:
  build:
    docker:
      # using custom image, see .circleci/images/primary/Dockerfile
      - image: circleci/python:3.8

    environment:
      TEST_RESULTS: /tmp/test-result
      COMPOSE_FILE: docker-compose-ci.yml

    steps:
      - checkout
      # - run:
      #     name: "Is docker available?"
      #     command: |
      #       which docker || echo "No docker"
      #       which docker-compose || echo "No docker compose"
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: "Docker compose up"
          command: |
            docker-compose -f ${COMPOSE_FILE} up -d
      - run:
          name: "Debug contents"
          command: |
            docker-compose -f ${COMPOSE_FILE} run django find /src
      - run:
          name: "Install packages"
          command: |
            docker-compose -f ${COMPOSE_FILE} run django poetry install
      - run:
          name: "Run tests"
          command: |
            mkdir test-results
            docker-compose -f ${COMPOSE_FILE} run -v $PWD/test-results/:/test-results django find /test-results -exec ls -l {} \+
            docker-compose -f ${COMPOSE_FILE} run -v $PWD/test-results/:/test-results --name tests django python -m pytest
            ls ./test_results/
      - store_test_results:
          path: test-results
